[package]
name = "bajsucks/rag"
description = "Simple, no-dependency ragdoll module that works on all rig types"
license = "Apache-2.0"
authors = ["baj"]
repository = "https://github.com/bajsucks/rag"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
